name: costy
description: Manage group expenses with ease.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dartz: ^0.9.1
  equatable: ^1.2.3
  decimal: ^0.3.5
  hive: ^1.4.3
  hive_flutter: ^0.3.1
  flutter_bloc: ^6.0.1
  get_it: ^4.0.4
  injectable: ^1.0.4
  intl: ^0.16.1
  flutter_platform_widgets: ^0.60.1
  oktoast: ^2.3.2
  share: ^0.6.4+3
  device_preview: ^0.4.7
  flutter_svg: ^0.18.1
  feather_icons_flutter: ^4.7.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  mockito: ^4.1.1
  hive_generator: ^0.7.1
  injectable_generator: ^1.0.4
  bloc_test: ^7.0.0
  build_runner:
  flutter_launcher_icons: ^0.7.5
  ozzie: ^2.2.3
  flutter_automation: ^1.3.3
  lint: ^1.2.0

dependency_overrides:
  analyzer: '0.39.14'

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/costy_icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lang/en.json
    - lang/pl.json
    - assets/images/grow.svg
    - assets/images/globe.svg
    - assets/images/users.svg
    - assets/images/idea.svg
    - assets/images/social.svg